# Generated by Django 2.1.5 on 2019-01-28 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_data', models.CharField(help_text='참고 데이터', max_length=16, null=True)),
                ('status_from', models.PositiveIntegerField(help_text='상태 변경 전', null=True)),
                ('status_to', models.PositiveIntegerField(help_text='상태 변경 후', null=True)),
                ('message', models.CharField(help_text='로그 메세지', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(default=None, help_text='삭제 일시', null=True)),
                ('status', models.PositiveIntegerField(help_text='상태', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(default=None, help_text='삭제 일시', null=True)),
                ('status', models.PositiveIntegerField(help_text='상태', null=True)),
                ('amount', models.IntegerField(help_text='결제 금액')),
                ('uid', models.CharField(help_text='주문 번호 (merchant_uid)', max_length=16, unique=True)),
                ('description', models.CharField(help_text='거래 상세 내용', max_length=150, null=True)),
                ('paid_at', models.DateTimeField(default=None, help_text='결제 일시', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(default=None, help_text='삭제 일시', null=True)),
                ('price', models.IntegerField(default=0, help_text='가격')),
                ('name', models.CharField(help_text='이름', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('deleted_at', models.DateTimeField(default=None, help_text='삭제 일시', null=True)),
                ('amount', models.IntegerField(default=0, help_text='금액')),
                ('order', models.ForeignKey(help_text='주문', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce_service.Order')),
                ('product', models.ForeignKey(help_text='주문 항목', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce_service.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.OneToOneField(help_text='결제 정보', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='ecommerce_service.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='ecommerce_service.Receipt', to='ecommerce_service.Product'),
        ),
    ]
